language: node_js
node_js:
  - 0.8
env:
  global:
    - GH_OWNER: ctoestreich
    - GH_PROJECT_NAME: knockout-validation-rule-engine
    #- secure: "dYoUzBT0sH1O9jX2N1rzxyOwOHMHDBA9ERrsov19H50KyLx13SGLxXauUcGo/7fww3V2Rc9bg/ejlxfapyGd2BCJuyRdj8krgcmXayehPF7cWEi/X+ttbTBfMu5uUSHBvOTGmbwchVoOTqDsTbVhzKI+M5CQ8/cO0eG67J2ziAk="
    - secure: dYoUzBT0sH1O9jX2N1rzxyOwOHMHDBA9ERrsov19H50KyLx13SGLxXauUcGo/7fww3V2Rc9bg/ejlxfapyGd2BCJuyRdj8krgcmXayehPF7cWEi/X+ttbTBfMu5uUSHBvOTGmbwchVoOTqDsTbVhzKI+M5CQ8/cO0eG67J2ziAk=
before_script:
  - npm install --quiet -g yo grunt-cli bower generator-travis-ci
  - bower install
script:
  - grunt --verbose
after_success:
  - git submodule add -b gh-pages https://${GH_TOKEN}@github.com/${GH_OWNER}/${GH_PROJECT_NAME} site > /dev/null 2>&1
  - cd site
  - if git checkout gh-pages; then git checkout -b gh-pages; fi
  - git rm -rf .
  - cp -R ../dist/* .
  - cp ../dist/.* .
  - git add -f .
  - git config user.email "acetrike@yahoo.com"
  - git config user.name "Christian Oestreich"
  - git commit -am "adding the yeoman build files to gh-pages"
  - git push https://${GH_TOKEN}@github.com/${GH_OWNER}/${GH_PROJECT_NAME} HEAD:gh-pages #> /dev/null 2>&1